all_config:
#Github-token-提交代码千万不能携带提交！
 github_token: 
 dingding:
   - enable: 1
   - webhook: https://oapi.dingtalk.com/robot/send?access_token=b33e5dbb84e62d703555d1d096d48ed8c130f30cb033f36dde214ced8cc82c1e
   - secretKey: SECd7a5daa62add4729ae698b4d2bad51c6360fe53ee11ba0b7220c7111e2a6fb24
   - app_name: dingding
 feishu:
   - enable: 0
   - webhook: xxx
   - app_name: feishu
 server:
   - enable: 0
   - sckey: 123123
   - app_name: server
 tgbot:
   - enable: 0
   - token: 123
   - group_id: 123
   - app_name: tgbot
 pushplus:
   - enable: 0
   - token: 123456
   - app_name: pushplus
 translate:
  - enable: 0
 black_user:
   - AlAIAL90
   - cirosantilli
   - lTbgykio
   - Dujltqzv
   - Daravai1234
