# GitHub监控配置文件
# 注意：提交代码时请确保不包含敏感信息（如GitHub Token）

all_config:
  # GitHub Token - 用于访问GitHub API
  # 请将此值设置为GitHub Secrets，不要直接提交到代码库
  github_token: 

  # 消息推送配置
  # 只需要启用一个推送渠道即可
  dingding:
    - enable: 1          # 1=启用，0=禁用
    - webhook: https://oapi.dingtalk.com/robot/send?access_token=
    - secretKey: 
    - app_name: dingding
  
  feishu:
    - enable: 0          # 1=启用，0=禁用
    - webhook: xxx       # 飞书机器人webhook
    - app_name: feishu
  
  tgbot:
    - enable: 0          # 1=启用，0=禁用
    - token: 123         # Telegram Bot Token
    - group_id: 123      # Telegram 群组ID
    - app_name: tgbot

  # 翻译配置
  translate:
    - enable: 0          # 1=启用，0=禁用
    # 启用后将翻译仓库描述等内容
    # 默认使用Google翻译，失败时自动降级到百度翻译
  
  # 百度翻译配置
  baidu_translate:
    - app_id: 
    - secret_key: 
    - api_key: 
  
  # 黑名单配置
  # 用于屏蔽垃圾用户和仓库
  # 从 https://github.com/BonjourFeng/Github-Search-Purification/blob/main/script.js 获取并定期更新
  black_user:
    - cirosantilli
    - wumaoland
    - codin-stuffs
    - cheezcharmer
    - gege-circle
    - zhaohmng-outlook-com
    - zaohmeing
    - Daravai1234
    - candice531033938
    - jk-ice-cream
    - jk-ice-cream-250
    - sky8964
    - pxvr-official
    - zpc1314521
    - jjzhang166
    - panbinibn
    - programthink
    - hello-world-1989
    - b0LBwZ7r5HOeh6CBMuQIhVu3-s-random-fork
    - thethetpvmy
    - wwwswitch520cc
    - shotoanqrob
    - sitempeanhkkwg
    - fukeluo
    - 1206256980
    - curees
    - yuoppo
    - Createree
    - vghl
    - wholedata
    - dunjian
    - mksshare
    - abshare
    - tpxdat
    - jhdyg
    - changfengqj
    - Dujltqzv
    - xmq1024
    - golade
    - kdjfhd
    - dkjhy
    - junsolg
    - dkjiiu
    - faithhow
    - yamtioy
    - zugzuc
    - lusvont
    - kenyatas
    - koeheu
    - juttama
    - duspub
    - wuqdid
    - visxud
    - suyfic
    - qokkod
    - roepuo
    - purfob
    - gitprocode
    - ynwynw
    - hanguodianying
    - hgyw
    - 69sm
    - urlapp
    - Augensternhx
    - urlweb
    - fuliso
    - nishjd
    - 36dshipin
    - haumpump
    - zhguoxmw
    - KoreanMovies
    - hanjutv
    - mamadepengyou
    - mamatouyunmuxuan
    - erzideqizi
    - wodeqizidejiejie
    - xiaoyizidemeng
    - qingyuzongheng
    - jiangnanerxi
    - hanguobiaomei
    - djhgy
    - XXOOBY
    - baoyu1024
    - kk234kkkk
    - 15923-ORIX
    - wutaed
    - webzhibo
    - apptuijian
    - follow666
    - yu90892
    - aconteet
    - getmal
    - itxinfei
    - mingtiana
    - midoushipin
    - paofushipin
    - yinghanshipin
    - GTVapp
    - huangyouquan
    - devlookme
    - audwq
    - jhdgy
    - di6gandh
    - shuangyuzhibo
    - lvchazhibo
    - xiaolanshipin
    - bofangqi
    - yingtaoshipin
    - xiangfeizhibo
    - lvchaApp
    - luoshenzhibo
    - yaojizhibo
    - mudanzhibo
    - aiaizhibo
    - gaochaoqwe
    - jiolde
    - lsdhw
    - kanavdaohang
    - harnh
    - kuadaner
    - wapquan
    - laoyeer
    - reteres
    - haoersn
    - zhengjianzhong0107
    - huaaweiCode
    - jianjian00001
    - m2ak-dev
    - yyzwz
    - froginwe11
    - luanmenglei
    - xijinping0
    - cyqqq
    - qldaisd
    - lTbgykio
    - yao270161651
    - jt0008jt0008
    - 15625103741
    - sky1234566778
    - chfucao
    - chifuyidaocao
    - updrmeltm
    - alice548
    - yazm000
    - cpnorg
    - tffygbu
    - Liberty-China
    - 1989CCP
    - liulihaocai
    - RevolutionaryCommitteeCPC
    - LeiyanLu
    - webdao
    - GC4WP
    - tu01
    - ziliao1
    - zzs70
    - ff2017
    - guitu2017
    - tu2017
    - wm001
    - wnel2017
    - dunhlino
    - nelaliox
    - jianjian3219
    - giteecode
    - 666bears
    - wang-buer
    - id681ilyg316
    - uhjid
    - usdui
    - uhskl
    - uyjks
    - uhskldf
    - itgsi5
    - uifskv
    - uhgask
    - igfkld
    - udsjd
    - ufodk
    - uigsjt
    - ighfrs
    - haivs
    - idrkkld
    - yuisju
    - uldydj
    - uyuek
    - tydfj
    - uuedif
    - ykwsw3
    - uigsi7
    - tyiis
    - ykeik
    - ukvdj
    - uyikl
    - ufzekg
    - yiksure
    - rhksgz
    - rthls
    - rhjaw
    - rehlxs
    - thzsgt
    - tdidst
    - eglct
    - tjkdyu
    - tjlks
    - tjjds
    - rllfs
    - rhkstd
    - yjscdr
    - servisee
    - ufsjzf
    - bvnbvnfgd
    - duliyingshi
    - calendi
    - mayeobey
    - QQMusic-Jay-Chou
    - boylovecomic
    - bt9527
    - FarmerChina
    - Waymon102092
    - baofx
    - biehd
    - moonpas
    - lyqilo
    - liliqh
    - hourv
    - xinfue
    - jijidianying
    - YuyanCai
    - jtdh
    - isdkxr
    - yhildyu
    - ykldyld
    - igsigk
    - uidekj
    - iufskw
    - udsjhf
    - tjkdx
    - rtkist
    - tjlsyh
    - euhf
    - rjzsht
    - rhkdzu
    - ehkkld
    - xzgfsw
    - iofgd
    - yufdk
    - ujkdub
    - iofgdsk
    - dyghikg
    - ugdskf
    - ifwaih
    - oigsiu
    - yjksku
    - yfdkkrf
    - thjsqd
    - yjsyhf
    - ydjsu6
    - igseyf
    - ujudy8
    - tykde
    - ykmdi8
    - yklzrf
    - uijdkd
    - yjkshc
    - tkajc
    - ykdzs
    - jklsx
    - ejldux
    - ifxspo
    - ogsvtf
    - ifdeu
    - yudfdi
    - ofssj
    - igegkx
    - ugfkd
    - ugdsk
    - udskts
    - yjlkdss
    - fkdryl
    - rtuyjsr
    - tus56f
    - yjdsd
    - yuet6h
    - ugtw
    - tlkxt
    - yesrs
    - ykkds
    - yjksu
    - yhyshs
    - xdzfby
    - yujzdh
    - znfl
    - kjiud
    - shijuezhishi
    - hy1980boy
    - ww0304
    - ZXCASD854
    - zfpdh
    - batiyadh
    - yinsedh
    - yyfxz
    - bllpooe
    - joodfer
    - qdmang
    - chaenet
    - mzsyv
    - kzhaoes
    - clnnews
    - kendnes
    - hongnews
    - luokez
    - li721-LY
    - itunsr
    - cctnews
    - htmle
    - xmmj2
    - younownews
    - 445435213
    - seseClub
    - enewse
    - wsnewse
    - qsnews
    - soasmoughroy
    - adminewhat
    - wsermusic
    - molingfer
    - zhihues
    - 95movies
    - 99fuli
    - qnewse
    - tareres
    - hukioip
    - Hochoclate713
    - ervnme
    - greenleaf8888
    - 93-days
    - doubanm
    - xhydh
    - fvckslvt
    - MDCM-FB
    - b08240
    - m3u8-ekvod
    - huan768468
    - SweeOBC
    - ningmengsuan7788
    - supperqb
    - idskjs
    - ifsird
    - gklksr
    - ifsjxr
    - ifskxt
    - ghjklsd
    - udsskd
    - tgsjk
    - ihgsk
    - ujsjk
    - ijhdf
    - fghhgks
    - udfae4
    - jujwdj
    - ydsdk
    - uyfgsj
    - ykkxrd
    - branono
    - hytcd
    - kjiuo
    - SaolApp
    - lourv
    - uisdlk
    - hutuhai
    - dengminna
    - whmnoe4j
    - txy9704
    - ufsjl
    - udsks
    - uifsjk
    - ygsaj
    - udsts
    - yurdek
    - ghklsr
    - ifsnx
    - ufskd
    - yujst6
    - ifsurjn
    - saoyagma
    - yusyrdk
    - uijhgr
    - geeeeeeeek
    - gfjklk
    - uiskv
    - ccccsp
    - rrrsp
    - udjxs
    - qiezisp
    - egklkd
    - t6korf
    - line915577
    - haijv
    - huaxinzhibo
    - haijiaofabuye
    - haijiaoshequ
    - HaijiaoCommunity
    - haijiao-app
    - fulibaike
    - lurmarp
    - entvasa
    - gotwib
    - hghkiiy121
    - gubcem
    - uijssu
    - yjhuk
    - yklsd
    - haijiaoWeb
    - winston779
    - tyukkst
    - ujsnmc
    - ygssk
    - igdkdy
    - qiezishiping
    - kjuhd
    - xiaogongzhuAPP
    - babyzhibo
    - yaojingzhibo
    - balizhibo
    - jiuaizhibo
    - liuyuezhibo
    - 69live
    - asidw
    - kuaimaoVIP
    - siguaha
    - mizhizhibo
    - lihzd
    - caomeizhibo
    - 36DAPP
    - luolisheApp
    - 69zhibo
    - jiejiezhibo
    - k8japan
    - buyaoshan
    - dk111222
    - fanbaovpn
    - HGcrowntiyu
    - 196tiyu
    - parryno
    - boyiscode
    - moonews
    - kim1528
    - tjqJ62cESiHPj6DdR6vXDAcPp
    - code-help-tutor
    - turbocanary
    - Ifem2BXvz4N4gh1gGn0bkR3Lp
    - R7w726fYrfritM7zPJCO
    - AlAIAL90

# 配置说明：
# 1. GitHub Token：用于访问GitHub API，建议通过GitHub Secrets配置
# 2. 推送渠道：可以选择钉钉、飞书或Telegram，只需启用一个即可
# 3. 翻译功能：启用后会翻译仓库描述等内容
# 4. 黑名单：用于屏蔽垃圾用户和仓库，定期从指定GitHub仓库更新
# 5. 运行频率：通过GitHub Actions的cron表达式配置，默认为每3分钟运行一次

# 使用建议：
# - 将敏感信息（如GitHub Token、机器人密钥）存储在GitHub Secrets中
# - 定期更新黑名单列表以确保屏蔽效果
# - 根据需要调整运行频率
# - 监控日志以确保服务正常运行
