name: Add Tools from Issue

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟运行一次
  workflow_dispatch:  # 支持手动触发

jobs:
  add-tools-from-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub pyyaml

      - name: Run update_tools_list script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python update_tools_list.py

      - name: Commit changes
        if: always()
        run: |
          git diff
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add tools_list.yaml
          git commit -m "Auto update tools_list.yaml from issue"
          git push
